domain_path: /home/issam/FPGA/repo/sdk/microzed/export/microzed/sw/domain_ps7_cortexa9_0
app_src_dir: /home/issam/tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
